# Python Fundamentals <a class="anchor" id="chapter1"></a>
Compilation of Python code that I've found useful. 

In [1]:
import sys 
print(f"* Python version:\n{sys.version}\n")

* Python version:
3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:37:07) [Clang 15.0.7 ]



## String Manipulation <a class="anchor" id="String_Manipulation"></a>

In [2]:
x="J"
print(f'Hello, {x}! How are you?')
print(f'Hello, {x.lower()}! How are you?')
print(f'Hello, {x}!','How are you?', sep="\n")
print(f"{2*2}")
print(f'{3.1415:.2}')

Hello, J! How are you?
Hello, j! How are you?
Hello, J!
How are you?
4
3.1


In [3]:
word = 'Hello'
print(word[0])    # one char of the word
print(word[0:1])  # one char of the word (same as above)
print(word[0:3])  # the first three char
print(word[:3])   # the first three char
print(word[-3:])  # the last three char
print(word[3:])   # all but the three first char
print(word[:-3])  # all but the three last character
print(word[::-1]) # reversed

H
H
Hel
Hel
llo
lo
He
olleH


In [4]:
word = "Hello World"
print(word.count('o'))           # counting the character “o” in the givenstring
word.split(' ')                  # Split on whitespace | ['Hello', 'World']
word.replace("Hello", "Goodbye") # 'Goodbye World'
print()
print(" ".join(word))           # add a whitespace between every char
print(":".join(word))           # add a : between every char
print(' '.join(reversed(word))) # d l r o W   o l l e H
print()
print(word.title())             # Hello World
print(word.capitalize())        # Hello world
print(word.swapcase())          # hELLO wORLD
print()
print(word.strip())  # removes from both ends
print(word.lstrip()) # removes leading characters (Left-strip)
print(word.rstrip()) # removes trailing characters (Right-strip)

2

H e l l o   W o r l d
H:e:l:l:o: :W:o:r:l:d
d l r o W   o l l e H

Hello World
Hello world
hELLO wORLD

Hello World
Hello World
Hello World


In [5]:
word.isalnum() #check if all char are alphanumeric 
word.isalpha() #check if all char in the string are alphabetic
word.isdigit() #test if string contains digits
word.istitle() #test if string contains title words
word.isupper() #test if string contains upper case
word.islower() #test if string contains lower case
word.isspace() #test if string contains spaces
word.endswith('d') #test if string endswith a d
word.startswith('H') #test if string startswith H

True

## Loops <a class="anchor" id="Loops"></a>

In [6]:
# range() function defaults to 0 as a starting value
for N in range(10):
    print(N, end=' ') # print all on same line
print()

start = 1
end = 11
inc = 2
for N in range(start, end, inc):
    print(N, end=' ') # print all on same line

0 1 2 3 4 5 6 7 8 9 
1 3 5 7 9 

In [7]:
h = [i for i in range(10)]
print(h)

# Select only even values
h = [i for i in h if (i % 2) == 0]
print(h)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]


In [8]:
# With the continue statement we can stop the current iteration of the loop, and continue with the next:
for n in range(20):
    if n % 2 == 0:
        continue
    print(n, end=' ')

1 3 5 7 9 11 13 15 17 19 

In [9]:
# With the break statement we can stop the loop before it has looped through all the items:
# Print Fibonacci sequence for values <= 100
a, b = 0, 1
amax = 100
L = []
while True:
    (a, b) = (b, a + b)
    if a > amax:
        break
    L.append(a)
print(L)

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]


In [10]:
print(*range(5))  # same as print(0, 1, 2, 3, 4)

0 1 2 3 4


enumerate

In [11]:
n = [{0, 296, 925, 415}, {1}, {2, 1318, 701, 12, 851, 797}, {522, 3, 1115}, {267, 4, 1023}, {5, 1384, 297, 749, 406, 1271, 985, 1404}, {569, 676, 6, 1359}]
for i, n_i in enumerate (n):
    print(i,n_i)

0 {0, 296, 925, 415}
1 {1}
2 {2, 851, 1318, 797, 12, 701}
3 {522, 3, 1115}
4 {267, 4, 1023}
5 {5, 1384, 297, 749, 406, 1271, 985, 1404}
6 {569, 676, 6, 1359}


## Data Types <a class="anchor" id="Data_Types"></a>
### Dictionaries

In [12]:
d = {'pi_approx': 3.14159265359,
     'e_approx': 2.71828182846,
     'c_approx': '299,792,458 m/s',
     'h_bar_approx': '6.62607004e-34 m^2 kg / s'}
print('d =', d)

d[0] = 0.0
d[1] = 1.0
d[-1] = -1.0
d['minus_one'] = d[-1]

print("\n", len(d), 'key-value pairs:', d)

# Deletion of keys:
d.pop('minus_one')

# Return key-value
print(d['c_approx'])

# List of dictionaries
data = [{'first':'Guido', 'last':'Van Rossum', 'YOB':1956},
        {'first':'Grace', 'last':'Hopper',     'YOB':1906},
        {'first':'Alan',  'last':'Turing',     'YOB':1912}]

sorted(data, key=lambda x: x['YOB'])
'''
[{'first': 'Grace', 'last': 'Hopper', 'YOB': 1906},
 {'first': 'Alan', 'last': 'Turing', 'YOB': 1912},
 {'first': 'Guido', 'last': 'Van Rossum', 'YOB': 1956}]
'''

# Sorting dictionaries
my_dict = {1: 2, 2: 10, "Hello": 1234}
print({key: value for key, value in sorted(my_dict.items(), key=lambda item: item[1])})
# {1: 2, 2: 10, 'Hello': 1234}

# Iterating over dictionaries
D = {k: v for v, k in enumerate('abcdef')}
print(D)


'''
Default Dictionaries
    Python's built-in dictionaries require you to check whether a key exists before updating it. 
    A way around that is to use default dict
'''
from collections import defaultdict
# you need to provide a "factory" function that the dictionary can use to create an initial value when the key does not exist.
d = defaultdict(int)
d['existing-key'] = 5 # Create one key-value pair
d['existing-key'] += 1 # Update
d['new-key'] += 1
print('\n', d)

d = {'pi_approx': 3.14159265359, 'e_approx': 2.71828182846, 'c_approx': '299,792,458 m/s', 'h_bar_approx': '6.62607004e-34 m^2 kg / s'}

 8 key-value pairs: {'pi_approx': 3.14159265359, 'e_approx': 2.71828182846, 'c_approx': '299,792,458 m/s', 'h_bar_approx': '6.62607004e-34 m^2 kg / s', 0: 0.0, 1: 1.0, -1: -1.0, 'minus_one': -1.0}
299,792,458 m/s
{1: 2, 2: 10, 'Hello': 1234}
{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5}

 defaultdict(<class 'int'>, {'existing-key': 6, 'new-key': 1})


### Lists

In [13]:
list_from_string = list('abcdefg')
print(list_from_string)

range_list = list(range(10))
print(range_list)

# Sorting lists, can also specify a sorting function with key=func
range_list.sort(reverse=True)
print(range_list)
range_list.sort(reverse=False)
print(range_list)

y = [1,2,3]
z = y.copy() # .copy() can be used to clone a list to be distinct references.
y.append(4)
print(z)

g = [i for i in range(10)] # 0 .. 9

from random import shuffle
shuffle(g) # permute randomly
print(g)

# Select only even values
h = [i for i in g if (i % 2) == 0]
print(h)

['a', 'b', 'c', 'd', 'e', 'f', 'g']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 2, 3]
[5, 2, 4, 1, 7, 0, 3, 8, 9, 6]
[2, 4, 0, 8, 6]


### Sets

In [14]:
# Sets are unordered, unchangeable, unindexed, and duplicates are not allowed.
# Python is free to reorder your values
s = 'quux'
s = set(s)
print(s)

s.add('p')
print(s)

# Removes a random element from a set.
s.pop()
print(s)

s.update({1,2,3})
print(s)

print('x' in s)
print('y' in s)

# Clears a set.
s.clear()
print(s)

A = {1, 2, 3, 4, 5}
B = {3, 4, 5, 6, 7}
print(A, '&', B, '==', A & B) # intersection
print(A, '|', B, '==', A | B) # union
print(A, '-', B, '==', A - B) # difference
print(A, '<', B, '==', A < B) # proper subset (use `<=` for subset, `>` or `>=` for superset, or '==' for equality)

{'u', 'q', 'x'}
{'u', 'p', 'q', 'x'}
{'p', 'q', 'x'}
{1, 'x', 2, 3, 'q', 'p'}
True
False
set()
{1, 2, 3, 4, 5} & {3, 4, 5, 6, 7} == {3, 4, 5}
{1, 2, 3, 4, 5} | {3, 4, 5, 6, 7} == {1, 2, 3, 4, 5, 6, 7}
{1, 2, 3, 4, 5} - {3, 4, 5, 6, 7} == {1, 2}
{1, 2, 3, 4, 5} < {3, 4, 5, 6, 7} == False


### Tuples <br>
Ordered, unchangeable, and allow duplicate values.

In [15]:
t = ("apple", "banana", "cherry")
print(t[0])
print(len(t))

apple
3


## Dates
Format code list - https://www.programiz.com/python-programming/datetime/strptime

In [16]:
from datetime import datetime
date_str = '2020-10-31'
date = datetime.strptime(date_str, '%Y-%m-%d')
print(date)
date_str = date.strftime("%Y-%m-%d")
print(date_str)

2020-10-31 00:00:00
2020-10-31


In [17]:
import datetime
dt_date = datetime.datetime.now()
print("In specified format:", dt_date.strftime("%A, %d %b %Y"))

In specified format: Sunday, 11 Aug 2024


## Random
https://docs.python.org/3/library/random.html

https://www.w3schools.com/python/module_random.asp

In [18]:
import random

# random.randint(start, stop)
print(random.randint(3, 9))

5


## Timeit <a class="anchor" id="Timeit"></a>

In [19]:
import time 
t1 = time.time()
print("Hi!")
t2 = time.time()
print(f"The time taken by print statement is {t2 - t1} seconds")

Hi!
The time taken by print statement is 8.082389831542969e-05 seconds


In [20]:
'''
%timeit - Measure execution time of small code snippets

from random import random
from decimal import Decimal

NUM_TRIALS = 0

print("Native arithmetic:")
A_native = [random() for _ in range(NUM_TRIALS)]
B_native = [random() for _ in range(NUM_TRIALS)]
%timeit [a+b for a, b in zip(A_native, B_native)]

print("\nDecimal package:")
A_decimal = [Decimal(a) for a in A_native]
B_decimal = [Decimal(b) for b in B_native]
%timeit [a+b for a, b in zip(A_decimal, B_decimal)]
'''

'\n%timeit - Measure execution time of small code snippets\n\nfrom random import random\nfrom decimal import Decimal\n\nNUM_TRIALS = 0\n\nprint("Native arithmetic:")\nA_native = [random() for _ in range(NUM_TRIALS)]\nB_native = [random() for _ in range(NUM_TRIALS)]\n%timeit [a+b for a, b in zip(A_native, B_native)]\n\nprint("\nDecimal package:")\nA_decimal = [Decimal(a) for a in A_native]\nB_decimal = [Decimal(b) for b in B_native]\n%timeit [a+b for a, b in zip(A_decimal, B_decimal)]\n'

## Misc <a class="anchor" id="Misc"></a>

### Windows Paths <a class="anchor" id="paths"></a>

In [21]:
path = r'C:\Users\eric_\Documents\Code\ChromeDriver\chromedriver.exe'

### Assertions

In [22]:
def KelvinToFahrenheit(Temperature):
   assert (Temperature >= 0),"Colder than absolute zero!"
   return ((Temperature-273)*1.8)+32

KelvinToFahrenheit(1)

-457.6

In [23]:

''' 
One line if statement
    value_when_true if condition else value_when_false
    
    Note: You cannot use Python if..elif..else block in one line. 
          Well you kind of can, but you shouldn't because it is hard to read.
'''
a = 1
b = 'Positive' if a > 0 else 'Negative'
print(b)

# Split string and assign variables to each part
helloworld = 'hello world'
hello, world = helloworld.split(' ')
print(hello,world)

Positive
hello world


# Pip
https://pip.pypa.io/en/stable/user_guide/

pip install --upgrade pip <br>
pip install SomePackage --upgrade <br>
pip uninstall SomePackage <br>
pip install sklearn --upgrade <br>

See outdate packages: <br>
pip list --outdated

Automatically upgrade all the outdated packages (that were installed using pip): <br>
`pip install $(pip list --outdated | awk '{ print $1 }') --upgrade`

<br>Another option<br>
`for i in  $(pip list --outdated --format=columns |tail -n +3|cut -d" " -f1); do pip install $i --upgrade; done`


## Regular Expressions
https://docs.python.org/3/howto/regex.html

Build/test expressions - https://regex101.com/

In [24]:
import re

In [25]:
##################
# METACHARACTERS #
##################
# [ ] - [abc] will match to any of the characters a, b, c. The same as [a-c]. Matches to metacharacters literally
#       [^5] will match any character except '5'. '^' only works if its the first character. [5^] will match to either 5 or '^'
#       [\s,.] any whitespace, or ',' or '.'
# \ - can be used to escape all metacharacters, \[] would match literally to '[]'
# . - any character except a newline character. alternate mode (re.DOTALL) will match to even newlines
#
#
# \d - any decimal, = [0-9]
# \D - non-digit, = [^0-9]
#
# \s - whitespace, = [ \t\n\r\f\v]
# \S - non-whitespace, = [^ \t\n\r\f\v]
#
# \w - alphanumeric, = [a-zA-Z0-9_]
# \W - non-alphanumeric, = [^a-zA-Z0-9_]
##################
# REPEAT METACHARS #
##################
# * - previous character can be matched zero or more times
#     ca*t will match ct, cat, caaaaat
#
# + - will match one or more times
#     ca+t will match cat, caaaaat
#
# ? - matches zero or one times. 
#     home-?brew matches homebrew or home-brew
#
# {m,n} - at least m, at most n repeats. Omitting 'm' will be interpreted as 0. 'n' will be infinity 
#         a/{1,3}b will match a/b, a//b, and a///b
##################
# | - 'or' operator, A|B
# ^ - beginning lines
# $ - end of a line
# \A - start of string
# \Z - end of string
# \b - beginning or end of a word(sequence of alphanumeric characters)
# \B - only matches when current position is not a word boundary

In [26]:
##################
# COMPILATION FLAGS #
##################
# ACSII, A - makes escapes like \w, \b, \s match only on ASCII characters
# DOTALL, S - make '.' match any character, including newlines
# IGNORECASE, I 
# MULTILINE, M - affecting '^', and '$'
 
pattern_matcher = re.compile ('fox', re.IGNORECASE)
matches = pattern_matcher.search ('The quick brown fox jumps over the lazy dog')

##################
# PATTERN MATCHERS #
##################
# match() - if RE matches at the beginning of the string
# search() - any location where the RE matches
# findall() - all substrings where RE matches, returns list
# finditer() - all substrings where RE matches, returns iterator

print (matches)
print (matches.group ()) # group() - return the string matched by RE
print (matches.start ()) # start() - return the starting position of the match
print (matches.end ())  # end() - return the ending position of the match
print (matches.span ()) # span() - return a tuple containing the (start,end) positions

<re.Match object; span=(16, 19), match='fox'>
fox
16
19
(16, 19)


In [27]:
##################
# LOOKAHEAD ASSERTIONS #
##################
# (?=...) - positive lookahead
# (?!...) - negative lookahead

In [28]:
# (?P<name>...) - named group. Grab the names with match.group(). match.groupdict() returns a dict of groups
#                 example: (?P<first>[a-zA-Z]+)

In [29]:
# Make the above more readable with a re.VERBOSE pattern
# Named groups <name>
re_names3 = re.compile ('''^
                           (?P<first>[a-zA-Z]+)
                           \s
                           (?P<middle>[a-zA-Z]+\s)?
                           \s*
                           (?P<last>[a-zA-Z]+)
                           $
                        ''',
                        re.VERBOSE)
print (re_names3.match ('Rich Vuduc').group ('first'))
print (re_names3.match ('Rich S Vuduc').group ('middle'))
print (re_names3.match ('Rich Salamander Vuduc').group ('last'))

Rich
S 
Vuduc


In [30]:
s = '(404) 555-1212'
pattern = '''
        ^\s*               # Leading spaces
        (?P<areacode>
           \d{3}-?         # "xxx" or "xxx-"
           | \(\d{3}\)\s*  # OR "(xxx) "
        )
        (?P<prefix>\d{3})  # xxx
        -?                 # Dash (optional)
        (?P<suffix>\d{4})  # xxxx
        \s*$               # Trailing spaces
    '''
matcher = re.compile(pattern, re.VERBOSE)
matches = matcher.match(s)
if matches is None:
    raise ValueError("'{}' is not in the right format.".format (s))
areacode = re.search('\d{3}', matches.group ('areacode')).group()
prefix = matches.group ('prefix')
suffix = matches.group ('suffix')
(areacode, prefix, suffix)

('404', '555', '1212')

## Numpy <a class="anchor" id="Numpy"></a>
https://numpy.org/

In [31]:
import numpy as np
from numpy.random import default_rng
print(np.__version__)

1.26.4


### Array creation

In [32]:
print(' np.zeros((3, 4))')
print(np.zeros((3, 4))) # creates an array from available memory space, and then fills it with zeros for your chosen dtype.

print('\n np.ones((3, 4))')
print(np.ones((3, 4)))

print('\n np.eye(3)')
print(np.eye(3))

print('\n np.diag([1, 2, 3])')
print(np.diag([1, 2, 3]))

print('\n np.empty((3, 4))')
print(np.empty((3, 4))) #  creates an array from available memory space, leaving whatever values happened to be hanging around in memory as the values.

 np.zeros((3, 4))
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 np.ones((3, 4))
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 np.eye(3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 np.diag([1, 2, 3])
[[1 0 0]
 [0 2 0]
 [0 0 3]]

 np.empty((3, 4))
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [33]:
a = np.array([1,2,3,4])
print(a,"\n")

a = np.arange(9).reshape(3, 3)
print(a,"\n")

# Create a two-dimensional array of size 3 rows x 4 columns:
b = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])
print(b,"\n")

[1 2 3 4] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 



### Random

In [34]:
rng = default_rng(12345)
#vals = rng.standard_normal(10)
np.random.seed(3)
x = np.random.randint(0, 20, 15) # 15 random ints in [0, 20)
print(x)

# Pull out an arbitrary subset of elements
inds = np.array([3, 7, 8, 12])
print(x[inds])

[10  3  8  0 19 10 11  9 10  6  0 12  7 14 17]
[ 0  9 10  7]


In [35]:
rand_A = np.random.randint(-10, 10, size=(4, 3)) # return random integers from -10 (inclusive) to 10 (exclusive)
print(rand_A)

[[-8 -8 -9]
 [ 9 -5 -2]
 [ 4 -9  0]
 [-3  1 -9]]


In [36]:
c = rng.integers(-10, 10, size=(4, 3)) # return random integers from -10 (inclusive) to 10 (exclusive)
print(c,"\n")

d = rng.integers(-10, 10, size=c.shape) # return random integers from -10 (inclusive) to 10 (exclusive)
print(d,"\n")

[[ 3 -6  5]
 [-4 -6  5]
 [ 2  3  9]
 [-3  6 -4]]

 

[[ 1  1 -6]
 [-7 -6  3]
 [ 2  8  4]
 [-6  8  8]] 



In [37]:
mins = [0, 0] # Two columns, minumum value
maxs = [[5], [5], [5]] # Three columns, max values
print(np.random.randint(mins, maxs, dtype=np.uint8))

mins = [5, 5] # Two columns, minumum value
maxs = [[10], [10], [10]] # Three columns, max values
print("\n",np.random.randint(mins, maxs, dtype=np.uint8))

[[3 1]
 [1 2]
 [0 0]]

 [[9 9]
 [6 6]
 [8 7]]


### Concatenate
https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [38]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
new_a = np.concatenate((a, b), axis=0)
print(new_a)

[[1 2]
 [3 4]
 [5 6]]


### Append
https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [39]:
'''Parameters:
 arr - Values are appended to a copy of this array.
 values - These values are appended to a copy of arr.
 axis (opt)
''' 

a = np.append(a, [7, 8, 9])
a

array([1, 2, 3, 4, 7, 8, 9])

### Astype

In [40]:
a = a.astype(float)
a

array([1., 2., 3., 4., 7., 8., 9.])

### Boolean Masks

In [41]:
print(x)
mask_mult_3 = (x > 0) & (x % 3 == 0)
print(mask_mult_3)

[10  3  8  0 19 10 11  9 10  6  0 12  7 14 17]
[False  True False False False False False  True False  True False  True
 False False False]


In [42]:
print(x[mask_mult_3])       # True values
print(np.where(mask_mult_3)) # True indeces 

[ 3  9  6 12]
(array([ 1,  7,  9, 11]),)


### Broadcasting
https://numpy.org/doc/stable/reference/ufuncs.html#broadcasting

Combine operations on numpy arrays that have different shapes but are _compatible_. Technically, `A` and `3` have different shapes: the former is a $4 \times 3$ matrix, while the latter is a scalar ($1 \times 1$). However, they are compatible because Numpy knows how to _extend_---or **broadcast**---the value 3 into an equivalent matrix object of the same shape in order to combine them.

In [43]:
print(c,"\n\n",c+3)
c_row_means = np.mean(c, axis=0)
print("\n", c_row_means)
c_col_means = np.mean(c, axis=1)
print("\n", c_col_means)

print(c.shape, c_row_means.shape)
print(c.shape, c_col_means.shape)
print()
c_col_means2 = np.reshape(c_col_means, (len(c_col_means), 1))
print(c_col_means2, "=>", c_col_means2.shape)
print()
print("A - A_col_means2\n\n", c, "\n-", c_col_means2) 
print("\n=>\n", c - c_col_means2)

[[ 3 -6  5]
 [-4 -6  5]
 [ 2  3  9]
 [-3  6 -4]] 

 [[ 6 -3  8]
 [-1 -3  8]
 [ 5  6 12]
 [ 0  9 -1]]

 [-0.5  -0.75  3.75]

 [ 0.66666667 -1.66666667  4.66666667 -0.33333333]
(4, 3) (3,)
(4, 3) (4,)

[[ 0.66666667]
 [-1.66666667]
 [ 4.66666667]
 [-0.33333333]] => (4, 1)

A - A_col_means2

 [[ 3 -6  5]
 [-4 -6  5]
 [ 2  3  9]
 [-3  6 -4]] 
- [[ 0.66666667]
 [-1.66666667]
 [ 4.66666667]
 [-0.33333333]]

=>
 [[ 2.33333333 -6.66666667  4.33333333]
 [-2.33333333 -4.33333333  6.66666667]
 [-2.66666667 -1.66666667  4.33333333]
 [-2.66666667  6.33333333 -3.66666667]]


### Indexing / Slicing
when you slice a Numpy array, you are actually creating a view into that array. That means modifications through the view will modify the original array.

In [44]:
A = np.array ([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]
              ], dtype=float)

print ("A[:, :] ==\n", A)
print ("\nA[0, :] ==\n", A[0, :])
print ("\nA[:, 0:1] ==\n", A[:, 0:1])
print ("\nA[:, 2:3] == \n", A[:, 2:3])

print ("\nAdd columns 0 and 2?")
a0 = A[:, 0:1]
a1 = A[:, 2:3]
print (a0 + a1)

A[:, :] ==
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

A[0, :] ==
 [1. 2. 3.]

A[:, 0:1] ==
 [[1.]
 [4.]
 [7.]]

A[:, 2:3] == 
 [[3.]
 [6.]
 [9.]]

Add columns 0 and 2?
[[ 4.]
 [10.]
 [16.]]


### Functions

In [45]:
npFunc = np.array([[0, 1, 2, 3],
                  [4, 5, 6, 7],
                  [8, 9, 10, 11]])
print(npFunc.ndim) # Number of array dimensions
print(npFunc.shape) # Rows x Columns
print(len(npFunc)) # Number of rows

# Math is straightforward sometimes
npFunc = npFunc*10
print("\n",npFunc)
npFunc = npFunc-1
print(npFunc,"\n",)

#print(np.mean(c.T, axis=1))
# aggregate all values
print("np.max =", np.max(npFunc))
print("np.min =",np.min(npFunc))
print("np.sum =",np.sum(npFunc))
print("np.mean =",np.mean(npFunc))
print("np.nanmean =",np.nanmean(npFunc)) # ignore NaN values
print("np.std =",np.std(npFunc))
print()
# aggregate along a dimension
print("Max in each column:", np.amax(npFunc, axis=0)) # i.e., aggregate along axis 0, the rows, producing column maxes
print("Max in each row:", np.amax(npFunc, axis=1)) # i.e., aggregate along axis 1, the columns, producing row maxes

2
(3, 4)
3

 [[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
[[ -1   9  19  29]
 [ 39  49  59  69]
 [ 79  89  99 109]] 

np.max = 109
np.min = -1
np.sum = 648
np.mean = 54.0
np.nanmean = 54.0
np.std = 34.52052529534663

Max in each column: [ 79  89  99 109]
Max in each row: [ 29  69 109]


### Universal functions
Universal functions apply a given function _elementwise_ to one or more Numpy objects.

[np.frompyfunc()](https://docs.scipy.org/doc/numpy/reference/generated/numpy.frompyfunc.html)

In [46]:
print(-npFunc,"\n")
print("np.abs(c)","\n",npFunc, "\n==>\n", np.abs(npFunc),"\n")

print("maximum(c,d)\n",np.maximum(npFunc,npFunc),"\n")

# Create universal functions
def f(x):
    from math import exp
    return exp(-(x**2))
f_np = np.frompyfunc(f,1,1)
print(f_np(npFunc))

[[   1   -9  -19  -29]
 [ -39  -49  -59  -69]
 [ -79  -89  -99 -109]] 

np.abs(c) 
 [[ -1   9  19  29]
 [ 39  49  59  69]
 [ 79  89  99 109]] 
==>
 [[  1   9  19  29]
 [ 39  49  59  69]
 [ 79  89  99 109]] 

maximum(c,d)
 [[ -1   9  19  29]
 [ 39  49  59  69]
 [ 79  89  99 109]] 

[[0.36787944117144233 6.639677199580735e-36 1.6584104776811452e-157 0.0]
 [0.0 0.0 0.0 0.0]
 [0.0 0.0 0.0 0.0]]


### Matrix Multiplication
You can only multiply two matrices if the number of columns in the first matrix equals the number of rows in the second matrix.

In [47]:
mm = [0, 1, 2, 3]
mm = np.array(mm)
MM = [[ 0,  1,  2,  3,  4,  5],
     [ 6,  7,  8,  9, 10, 11],
     [12, 13, 14, 15, 16, 17],
     [18, 19, 20, 21, 22, 23]]
MM = np.array(MM)
print(mm.shape, MM.shape)
print("\n",mm)
mm = np.expand_dims(mm, axis=-1) # Add an extra dimension in the last axis.
print(mm,"\n")
print(mm.shape, MM.shape)
print(mm*MM)
#print(mm.dot(MM)) # shapes (4,1) and (4,6) not aligned: 1 (dim 1) != 4 (dim 0)


(4,) (4, 6)

 [0 1 2 3]
[[0]
 [1]
 [2]
 [3]] 

(4, 1) (4, 6)
[[ 0  0  0  0  0  0]
 [ 6  7  8  9 10 11]
 [24 26 28 30 32 34]
 [54 57 60 63 66 69]]


## Pandas <a class="anchor" id="Pandas"></a>
https://pandas.pydata.org/pandas-docs/stable/user_guide/options.html#available-options

In [48]:
import pandas as pd
from io import StringIO
from IPython.display import display
import sys

print(f"* pandas version: {pd.__version__}")

* pandas version: 2.2.1


Settings

In [49]:
print("Display Rows:",pd.get_option("display.max_rows"))
print("Display Columns:",pd.get_option("display.max_columns"))
print("Display Precision:",pd.get_option("precision"))
#pd.set_option("display.max_rows", 5)
#pd.set_option("display.max_columns", 5)
#pd.set_option("precision", 5) # display precision in terms of decimal places
#pd.set_option("expand_frame_repr", True)
#pd.set_option("chop_threshold", 0) # what level pandas rounds to zero when it displays a Series

Display Rows: 60
Display Columns: 20


OptionError: Pattern matched multiple keys

### DataFrame Creation

In [49]:
df = pd.DataFrame() # empty 

covid = pd.DataFrame({'Timestamp': ['2020-03-12', '2020-03-17', '2020-03-11', '2020-03-15', '2020-03-18', '2020-03-16', '2020-03-13','2020-03-14'], 
              'ST': ['GA', 'GA', 'GA','GA','GA', 'GA', 'GA','GA'],
              'Confirmed': [42,121,17,66,146,99,31,31]})

Read_table / read_csv / read_...
https://pandas.pydata.org/pandas-docs/version/0.18.1/generated/pandas.read_table.html

In [50]:
#df = pd.read_html(url)
#df = pd.read_json(path)
#df = pd.read_sql(query,connection)
#df = pd.read_excel('name.xlsx')
#df = pd.read_clipboard # eg from Excel copy

faithful = pd.read_table("http://www.stat.cmu.edu/~larry/all-of-statistics/=data/faithful.dat",
                         skiprows=20, delim_whitespace=True)

A_csv = """country,year,cases
Afghanistan,1999,745
Brazil,1999,37737
China,1999,212258
Afghanistan,2000,2666
Brazil,2000,80488
China,2000,213766"""
with StringIO(A_csv) as fp:
    A = pd.read_csv(fp)
B_csv = """country,year,population
Afghanistan,1999,19987071
Brazil,1999,172006362
China,1999,1272915272
Afghanistan,2000,20595360
Brazil,2000,174504898
China,2000,1280428583"""
with StringIO(B_csv) as fp:
    B = pd.read_csv(fp)
C = A.merge(B, on=['country', 'year'])
with StringIO("""x,y,z
bug,1,d
rug,2,d
lug,3,d
mug,4,d""") as fp:
    D = pd.read_csv(fp)
with StringIO("""x,y,w
hug,-1,e
smug,-2,e
rug,-3,e
tug,-4,e
bug,1,e""") as fp:
    E = pd.read_csv(fp)

Random Data

In [51]:
df = (pd.DataFrame(np.random.rand(10, 6),
                  columns = list('ABCDEF')) - 0.5).cumsum()
df['Group'] = [np.random.choice(list('abcd')) for _ in range(len(df))]
df['Date'] = pd.date_range('1/1/2017', periods=len(df), freq='D')
display(df)

A         B         C         D         E         F Group       Date
0  0.393065  0.218422 -0.479385 -0.357283 -0.174694  0.308929     a 2017-01-01
1  0.292056  0.143124 -0.565667 -0.070144  0.038872 -0.167953     a 2017-01-02
2  0.107823  0.205894 -0.317509  0.039479 -0.257774 -0.014322     a 2017-01-03
3  0.270510  0.576966 -0.006282 -0.086396 -0.682573  0.246256     a 2017-01-04
4 -0.165721  0.918007  0.186352 -0.140495 -0.820233  0.262351     a 2017-01-05
5 -0.208388  1.226369  0.002637  0.203292 -0.830942  0.302470     d 2017-01-06
6  0.117740  1.247974 -0.354764  0.005555 -0.523919  0.121965     b 2017-01-07
7 -0.361035  1.230419 -0.828738  0.011129 -0.105889 -0.171069     d 2017-01-08
8  0.064698  1.007742 -1.152676  0.501431  0.086762  0.081072     a 2017-01-09
9 -0.319085  0.593743 -0.987051  0.331002 -0.051588  0.107183     a 2017-01-10

### Append / Drop / Filter / Impute

Append / Add Columns <br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.append.html

In [52]:
E['pi'] = 3.14# Creates a new column (variable) named ‘x’ and sets all values in column = 3.
display(E)
del E['pi']

# Adding an entire row
new_row = {0:'shrug', 'w':-5, 'x':'e'}
E = E.append(new_row, ignore_index=True)

# Setting specific cell value
#df.at[row,col]
E.at[0,0] = 'at 0,0 test'
E.loc[1,0] = 'loc 0,1 test'

display(E)

x  y  w    pi
0   hug -1  e  3.14
1  smug -2  e  3.14
2   rug -3  e  3.14
3   tug -4  e  3.14
4   bug  1  e  3.14

x    y   w             0
0   hug -1.0   e   at 0,0 test
1  smug -2.0   e  loc 0,1 test
2   rug -3.0   e           NaN
3   tug -4.0   e           NaN
4   bug  1.0   e           NaN
5     e  NaN  -5         shrug

Drop/Delete Columns <br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop.html <br>

In [53]:
display(C)
dropdf = C.copy()

print('Drop indexes: \ndropdf.drop([0,1]')
dropdf = dropdf.drop([0,1]) 
display(dropdf)

print('Drop columns: \ndropdf.drop(["'"year"'"], axis=1)')
dropdf = dropdf.drop(['year'], axis=1) 
display(dropdf)

print('del dropdf["'"cases"'"]')
del dropdf['cases']
display(dropdf)

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

Drop indexes: 
dropdf.drop([0,1]


country  year   cases  population
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

Drop columns: 
dropdf.drop(["year"], axis=1)


country   cases  population
2        China  212258  1272915272
3  Afghanistan    2666    20595360
4       Brazil   80488   174504898
5        China  213766  1280428583

del dropdf["cases"]


country  population
2        China  1272915272
3  Afghanistan    20595360
4       Brazil   174504898
5        China  1280428583

Drop Duplicates <br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.drop_duplicates.html

In [54]:
dropdf = C.copy()

# No duplicates so bad example
dropdf = C.copy()
dropdf = dropdf.drop_duplicates()
display(dropdf)

# Drop duplicates by specific column
print('Drop duplicates: \ndropdf.drop_duplicates(subset=["'"country"'"])')
dropdf = dropdf.drop_duplicates(subset=['country'])
display(dropdf)
# .reset_index(drop=True)

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

Drop duplicates: 
dropdf.drop_duplicates(subset=["country"])


country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272

Filter <br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.filter.html

In [55]:
filter_df = pd.DataFrame(np.array(([1, 2, 3], [4, 5, 6])),
                  index=['mouse', 'rabbit'],
                  columns=['one', 'two', 'three'])

display(filter_df.filter(items=['one']))           # by column
display(filter_df.filter(items=['mouse'], axis=0)) # by row
display(filter_df.filter(like='o'))                # non-exact match
display(filter_df.filter(regex='e$'))              # using regular expression (e$ matches to strings that end in e)

one
mouse     1
rabbit    4

one  two  three
mouse    1    2      3

one  two
mouse     1    2
rabbit    4    5

one  three
mouse     1      3
rabbit    4      6

Impute (Missing Data) <br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html

isna(obj) - Detect missing values for an array-like object. <br>
isnull(obj) - Detect missing values for an array-like object. <br>
notna(obj) - Detect non-missing values for an array-like object. <br>
notnull(obj) - Detect non-missing values for an array-like object. <br>

In [56]:
missingdf = D.merge(E, on=['x', 'y'], how='outer')
display(missingdf)

print("\ndf.isnull().sum()",)
print(missingdf.isnull().sum())

# Only works on numeric data
#print("\ndf.ifillna(0).astype(int)",)
#display(missingdf['z'].fillna(0).astype(int))

x    y    z    w             0
0   bug  1.0    d    e           NaN
1   rug  2.0    d  NaN           NaN
2   lug  3.0    d  NaN           NaN
3   mug  4.0    d  NaN           NaN
4   hug -1.0  NaN    e   at 0,0 test
5  smug -2.0  NaN    e  loc 0,1 test
6   rug -3.0  NaN    e           NaN
7   tug -4.0  NaN    e           NaN
8     e  NaN  NaN   -5         shrug


df.isnull().sum()
x    0
y    1
z    5
w    3
0    6
dtype: int64


### Apply<a class="anchor" id="Apply"></a>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html

In [57]:
display(C)
G = C.copy() # If you do not use copy function the original data frame is modified
G['year'] = G['year'].apply(lambda x: "'{:02d}".format(x % 100))
display(G)

##################################################
# Using apply(axis=1) for rows in dataframe
##################################################
def div(row):
    return row['cases'] / row['population']

h = G.copy()
h['prevalence'] = h[['cases','population']].apply(div,axis=1)
display(h)

##################################################
# groupby().apply pulls a row as a series
##################################################
def daily_window_one_df(df, days):
    from numpy import nan
    df_new = df.sort_values(by="Timestamp")
    df_new["Sums"] = df_new["Confirmed"]
    for k in range(1, days):
        df_new["Sums"].iloc[k:] += df_new["Confirmed"].iloc[:-k].values
    df_new["Sums"] /= days
    df_new.rename(columns={"Sums": "Avg"}, inplace=True)
    return df_new.iloc[days-1:]

covid.groupby("ST").apply(lambda x: daily_window_one_df(x, 3)).reset_index(drop=True)

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

country year   cases  population
0  Afghanistan  '99     745    19987071
1       Brazil  '99   37737   172006362
2        China  '99  212258  1272915272
3  Afghanistan  '00    2666    20595360
4       Brazil  '00   80488   174504898
5        China  '00  213766  1280428583

country year   cases  population  prevalence
0  Afghanistan  '99     745    19987071    0.000037
1       Brazil  '99   37737   172006362    0.000219
2        China  '99  212258  1272915272    0.000167
3  Afghanistan  '00    2666    20595360    0.000129
4       Brazil  '00   80488   174504898    0.000461
5        China  '00  213766  1280428583    0.000167

Timestamp  ST  Confirmed         Avg
0  2020-03-13  GA         31   30.000000
1  2020-03-14  GA         31   34.666667
2  2020-03-15  GA         66   42.666667
3  2020-03-16  GA         99   65.333333
4  2020-03-17  GA        121   95.333333
5  2020-03-18  GA        146  122.000000

In [58]:
apply_df = pd.DataFrame({'a':[1,2,3], 'b':[{'c':1}, {'d':3}, {'c':5, 'd':6}]})
display(apply_df)
display(apply_df['b'].apply(pd.Series))
pd.concat([apply_df.drop(['b'], axis=1), apply_df['b'].apply(pd.Series)], axis=1)

a                 b
0  1          {'c': 1}
1  2          {'d': 3}
2  3  {'c': 5, 'd': 6}

c    d
0  1.0  NaN
1  NaN  3.0
2  5.0  6.0

a    c    d
0  1  1.0  NaN
1  2  NaN  3.0
2  3  5.0  6.0

### Indexing  <a class="anchor" id="Indexing"></a>

https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html

https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.reset_index.html

In [59]:
# Bring the index out as a column
# df.reset_index(inplace=True)
display(C)

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

In [60]:
# [start, stop, step]
# First 5 rows
display(C[:5])

# All but the last row
display(C[:-1:])

# Even number rows
display(C[::2])

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898

country  year   cases  population
0  Afghanistan  1999     745    19987071
2        China  1999  212258  1272915272
4       Brazil  2000   80488   174504898

Select columns with [ ]

Str.contains matches on a partial match -
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.str.contains.html

whereas C['country'] == 'Brazil' finds exact matches only

In [61]:
#series = df[col]
#df = df[[col]]
#df = df[[col_a , col_b]]

# Using column names
display(C[['year','cases']])

# Using column names to filter
display(C[C['year'] == 2000])

# Using 2 conditions to filter
C[(C['year'] == 1999) & (C['country'] == 'Afghanistan')]
# Might be better to use loc/iloc
#display(C[ (C['year'] == 2000) and (C['country'] == Afghanistan) ])

display(C[C['country'].str.contains('Braz')])
display(C[C['country'] == 'Brazil'])

year   cases
0  1999     745
1  1999   37737
2  1999  212258
3  2000    2666
4  2000   80488
5  2000  213766

country  year   cases  population
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

country  year  cases  population
1  Brazil  1999  37737   172006362
4  Brazil  2000  80488   174504898

country  year  cases  population
1  Brazil  1999  37737   172006362
4  Brazil  2000  80488   174504898

isin <br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isin.html

In [62]:
countries_I_want_2_see = ['Brazil', 'Afghanistan']
C['country'].isin(countries_I_want_2_see)

0     True
1     True
2    False
3     True
4     True
5    False
Name: country, dtype: bool

In [63]:
# Matching on two columns at once
#  matches_city_st = (ratings['city'] + ', ' + ratings['state']) == city_st

### iloc  <a class="anchor" id="iloc"></a>
primarily integer position based (from 0 to length-1 of the axis), but may also be used with a boolean array. .iloc will raise IndexError if a requested indexer is out-of-bounds, except slice indexers which allow out-of-bounds indexing. (this conforms with Python/NumPy slice semantics). Allowed inputs are:

- An integer e.g. 5.
- A list or array of integers [4, 3, 0].
- A slice object with ints 1:7.
- A boolean array (any NA values will be treated as False).
- A callable function with one argument (the calling Series or DataFrame) and that returns valid output for indexing (one of the above).

In [64]:
display(C)
display(C.iloc[1:2])

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

country  year  cases  population
1  Brazil  1999  37737   172006362

### loc  <a class="anchor" id="loc"></a>
Label based, but may also be used with a boolean array. .loc will raise KeyError when the items are not found. Allowed inputs are:

- A single label, e.g. 5 or 'a' (Note that 5 is interpreted as a label of the index. This use is not an integer position along the index.).

- A list or array of labels ['a', 'b', 'c'].

- A slice object with labels 'a':'f' (Note that contrary to usual Python slices, both the start and the stop are included, when present in the index! See Slicing with labels and Endpoints are inclusive.)

- A boolean array (any NA values will be treated as False).

- A callable function with one argument (the calling Series or DataFrame) and that returns valid output for indexing (one of the above).

In [65]:
display(C)

#Syntax
#df.loc[row, col]

# Select by columns
display(C.loc[:, ['country','year']]) # Equivalent to C[['country', 'year']]

# Select by index
display(C.loc[0:2])

# Selecting by column and index
display(C.loc[3:, ['cases','population']])

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

country  year
0  Afghanistan  1999
1       Brazil  1999
2        China  1999
3  Afghanistan  2000
4       Brazil  2000
5        China  2000

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272

cases  population
3    2666    20595360
4   80488   174504898
5  213766  1280428583

In [66]:
# Selecting by boolean array
display(C.loc[:, ['year']] == 2000)
#display(C.loc[:, C.loc[:, ['year']] == 2000])

# All but one columns
C.loc[:, C.columns != 'country']

year
0  False
1  False
2  False
3   True
4   True
5   True

year   cases  population
0  1999     745    19987071
1  1999   37737   172006362
2  1999  212258  1272915272
3  2000    2666    20595360
4  2000   80488   174504898
5  2000  213766  1280428583

## iterrate

iteritems

In [67]:
for column_name, item in C.iteritems():
    print(column_name,"\t|\t",item[0])

country 	|	 Afghanistan
year 	|	 1999
cases 	|	 745
population 	|	 19987071


iterrows <br>
You should never modify something you are iterating over.
Iterrows returns a Series for each row, it does not preserve dtypes across the rows
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iterrows.html#pandas.DataFrame.iterrows

In [68]:
for index, row in C.iterrows():
    print(index,"\t|\t",row[0])

0 	|	 Afghanistan
1 	|	 Brazil
2 	|	 China
3 	|	 Afghanistan
4 	|	 Brazil
5 	|	 China


itertuples  <br>
Generally faster than iterrows
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.itertuples.html

In [69]:
for row in C.itertuples():
    print(row)
print("\nindex=False")    
for row in C.itertuples(index=False):
    print(row)
print("\nname='t'")   
for row in C.itertuples(name='t'):
    print(row)

Pandas(Index=0, country='Afghanistan', year=1999, cases=745, population=19987071)
Pandas(Index=1, country='Brazil', year=1999, cases=37737, population=172006362)
Pandas(Index=2, country='China', year=1999, cases=212258, population=1272915272)
Pandas(Index=3, country='Afghanistan', year=2000, cases=2666, population=20595360)
Pandas(Index=4, country='Brazil', year=2000, cases=80488, population=174504898)
Pandas(Index=5, country='China', year=2000, cases=213766, population=1280428583)

index=False
Pandas(country='Afghanistan', year=1999, cases=745, population=19987071)
Pandas(country='Brazil', year=1999, cases=37737, population=172006362)
Pandas(country='China', year=1999, cases=212258, population=1272915272)
Pandas(country='Afghanistan', year=2000, cases=2666, population=20595360)
Pandas(country='Brazil', year=2000, cases=80488, population=174504898)
Pandas(country='China', year=2000, cases=213766, population=1280428583)

name='t'
t(Index=0, country='Afghanistan', year=1999, cases=745, p

### Datetime <a class="anchor" id="Datetime"></a>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html?highlight=to_datetime

In [70]:
from datetime import date
df = pd.DataFrame({'year': [2015, 2016],
                   'month': [2, 3],
                   'day': [4, 5]})
display(df)
df['datetime']=pd.to_datetime(df)
display(df)

df['Month'] = df.datetime.dt.month
df['Day'] = df.datetime.dt.day
df['Year'] = df.datetime.dt.year
#df['Week Number'] = df.datetime.dt.isocalendar().week
df['Day of Week'] = df.datetime.dt.dayofweek
df['Day Name'] = df.datetime.dt.day_name()
df['Month Name'] = df.datetime.dt.month_name()
display(df)

#df[pd.to_datetime(df['datetime']) > pd.Timestamp(date(2015,12,12))]
df[df['datetime'] > pd.Timestamp(date(2015,12,12))]
df[df['datetime'] > pd.Timestamp('2015,12,12')]

year  month  day
0  2015      2    4
1  2016      3    5

year  month  day   datetime
0  2015      2    4 2015-02-04
1  2016      3    5 2016-03-05

year  month  day   datetime  Month  Day  Year  Day of Week   Day Name  \
0  2015      2    4 2015-02-04      2    4  2015            2  Wednesday   
1  2016      3    5 2016-03-05      3    5  2016            5   Saturday   

  Month Name  
0   February  
1      March

year  month  day   datetime  Month  Day  Year  Day of Week  Day Name  \
1  2016      3    5 2016-03-05      3    5  2016            5  Saturday   

  Month Name  
1      March

Python strftime cheatsheet: https://strftime.org/

Example: '05SEP2014:00:00:00.000'='%d%b%Y:%H:%M:%S.%f'

In [139]:
day = pd.DataFrame({'day': ['4/11/2021']})
day['day'] =  pd.to_datetime(day['day'])
display(day)
day.info()

day
0 2021-04-11

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   day     1 non-null      datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 136.0 bytes


In [71]:
# Between 2 dates
#df[(df['Transaction_Date'] >= pd.Timestamp('2021-08-01')) & (df['Transaction_Date'] < pd.Timestamp('2021-09-01'))]

df = df.set_index('datetime')
display(df)
date_index_filter = df.index.to_series().between('2015-01-01', '2015-07-01')
df[date_index_filter]

year  month  day  Month  Day  Year  Day of Week   Day Name  \
datetime                                                                 
2015-02-04  2015      2    4      2    4  2015            2  Wednesday   
2016-03-05  2016      3    5      3    5  2016            5   Saturday   

           Month Name  
datetime               
2015-02-04   February  
2016-03-05      March

year  month  day  Month  Day  Year  Day of Week   Day Name  \
datetime                                                                 
2015-02-04  2015      2    4      2    4  2015            2  Wednesday   

           Month Name  
datetime               
2015-02-04   February

Timedelta <br>
https://pandas.pydata.org/docs/reference/api/pandas.Timedelta.html

In [72]:
# Zero date
#datetime.datetime(1900, 1, 1, 2, 0)
#HrsEarly = HrsEarly - datetime.datetime(1900, 1, 1)

#df['datetime'].iloc[0]
#dt_demo.total_seconds()

### Dictionary Conversions

DF to Dict

In [73]:
df1 = pd.DataFrame([['a', 1], ['b', 2]], columns=['letter', 'number'])
df2 = pd.DataFrame([['c', 3], ['d', 4]], columns=['letter', 'number'])
df3 = pd.concat([df1, df2])
display(df3)

dict(zip(df3['letter'], df3['number']))

letter  number
0      a       1
1      b       2
0      c       3
1      d       4

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

Dict to DF
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html

In [74]:
### the keys of the dict become the DataFrame columns:
df3 = pd.DataFrame.from_dict(df3)#,orient='index')
display(df3)


#Specify orient='index' to create the DataFrame using dictionary keys as rows. Column names can be specified manually
d = {'row1': ['pi_approx', 3.14159265359],
     'row2': ['e_approx', 2.71828182846],
     'row3': ['c_approx', '299,792,458 m/s'],
     'row4': ['h_bar_approx', '6.62607004e-34 m^2 kg / s']}
d = pd.DataFrame.from_dict(d, orient='index', columns=['name', 'value'])
display(d)

letter  number
0      a       1
1      b       2
0      c       3
1      d       4

name                      value
row1     pi_approx                   3.141593
row2      e_approx                   2.718282
row3      c_approx            299,792,458 m/s
row4  h_bar_approx  6.62607004e-34 m^2 kg / s

### Functions 
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html

In [75]:
display(C.info)
C.info()

<bound method DataFrame.info of        country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583>

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   country     6 non-null      object
 1   year        6 non-null      int64 
 2   cases       6 non-null      int64 
 3   population  6 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 412.0+ bytes


In [76]:
print("\n",C.describe())
print("df.shape \t",  C.shape )
print("df.index \t",  C.index )
print("C.columns \t", C.columns)
print("C.columns \t", C.columns)


               year          cases    population
count     6.000000       6.000000  6.000000e+00
mean   1999.500000   91276.666667  4.900729e+08
std       0.547723   98661.891273  6.131303e+08
min    1999.000000     745.000000  1.998707e+07
25%    1999.000000   11433.750000  5.844811e+07
50%    1999.500000   59112.500000  1.732556e+08
75%    2000.000000  179315.500000  9.983127e+08
max    2000.000000  213766.000000  1.280429e+09
df.shape 	 (6, 4)
df.index 	 Int64Index([0, 1, 2, 3, 4, 5], dtype='int64')
C.columns 	 Index(['country', 'year', 'cases', 'population'], dtype='object')
C.columns 	 Index(['country', 'year', 'cases', 'population'], dtype='object')


In [77]:
C.year.value_counts()

2000    3
1999    3
Name: year, dtype: int64

In [78]:
display(C.head(1))
display(C.tail(1))
display(C.head(5).tail(1))
display(C.sample(3))

country  year  cases  population
0  Afghanistan  1999    745    19987071

country  year   cases  population
5   China  2000  213766  1280428583

country  year  cases  population
4  Brazil  2000  80488   174504898

country  year  cases  population
3  Afghanistan  2000   2666    20595360
1       Brazil  1999  37737   172006362
4       Brazil  2000  80488   174504898

Maths <br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sum.html

In [79]:
print(".sum() \t", C.sum() )

.sum() 	 country       AfghanistanBrazilChinaAfghanistanBrazilChina
year                                                 11997
cases                                               547660
population                                      2940437546
dtype: object


Column element-wise methods

In [80]:
print(C['cases'].sum() )
print()
print(C['cases'].round(decimals=0) )
print(C['cases'].abs() )

print("idxmin()\t", (C['cases']).idxmin() ) # Return the index of the minimum.
print("idxmax()\t", (C['cases']).idxmax() ) # Return the index of the maximum.

547660

0       745
1     37737
2    212258
3      2666
4     80488
5    213766
Name: cases, dtype: int64
0       745
1     37737
2    212258
3      2666
4     80488
5    213766
Name: cases, dtype: int64
idxmin()	 0
idxmax()	 5


https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.all.html

In [81]:
# df.any() and df.all()
print(C['cases'] < 1000,"\n")
print("df.all() Return True if all elements are True.")
print((C['cases'] < 1000).all(),"\n") 
print("df.any() Returns True if any elements are True.")
print((C['cases'] < 1000).any(),"\n")

0     True
1    False
2    False
3    False
4    False
5    False
Name: cases, dtype: bool 

df.all() Return True if all elements are True.
False 

df.any() Returns True if any elements are True.
True 



https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.astype.html
https://numpy.org/doc/stable/reference/generated/numpy.dtype.html#numpy.dtype

In [82]:
print(C.dtypes)
C['cases'] = C['cases'].astype(int) # int32 by default
print("\n",C.dtypes)
# .astype('int32')
# .astype('int64')
# .astype('category')

country       object
year           int64
cases          int64
population     int64
dtype: object

 country       object
year           int64
cases          int32
population     int64
dtype: object


### Join / Merge / Concate

Concate <br>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html

In [83]:
df1 = pd.DataFrame([['a', 1], ['b', 2]], columns=['letter', 'number'])
#       letter  number
# 0      a       1
# 1      b       2
df2 = pd.DataFrame([['c', 3], ['d', 4]], columns=['letter', 'number'])
#       letter  number
# 0      c       3
# 1      d       4
df3 = pd.concat([df1, df2])

Join
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.join.html#pandas.DataFrame.join<br>

Merge

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html

This default behavior of keeping only rows that match both input frames is an example of what relational database systems call an _inner-join_ operation. But there are several other types of joins.

- _Inner-join (`A`, `B`)_ (default): Keep only rows of `A` and `B` where the on-keys match in both.
- _Outer-join (`A`, `B`)_: Keep all rows of both frames, but merge rows when the on-keys match. For non-matches, fill in missing values with not-a-number (`NaN`) values.
- _Left-join (`A`, `B`)_: Keep all rows of `A`. Only merge rows of `B` whose on-keys match `A`.
- _Right-join (`A`, `B`)_: Keep all rows of `B`. Only merge rows of `A` whose on-keys match `B`.

You can use `merge`'s `how=...` parameter, which takes the (string) values, `'inner`', `'outer'`, `'left'`, and `'right'`. Here are some examples of these types of joins.

In [84]:
mergeA = pd.DataFrame({'a': ['a1', 'a2'], 
                       'b': ['b1', 'b2']})
mergeB = pd.DataFrame({'a': ['a1', 'a2','a3'], 
                       'c': ['c1', 'c2','c3']})
print("\n=== Inner-join ===")
display(mergeA.merge(mergeB, on=['a']))
print("\n=== Outer-join ===")
display(mergeA.merge(mergeB, on=['a'], how='outer'))
print("\n=== Left-join ===")
display(mergeA.merge(mergeB, on=['a'], how='left'))
print("\n=== Right-join ===")
display(mergeA.merge(mergeB, on=['a'], how='right'))


mergeC = pd.DataFrame({'d': ['a1', 'a2','a3'], 
                       'c': ['c1', 'c2','c3']})
pd.merge(mergeA, mergeC, left_on=['a'], right_on=['d'])


=== Inner-join ===


a   b   c
0  a1  b1  c1
1  a2  b2  c2


=== Outer-join ===


a    b   c
0  a1   b1  c1
1  a2   b2  c2
2  a3  NaN  c3


=== Left-join ===


a   b   c
0  a1  b1  c1
1  a2  b2  c2


=== Right-join ===


a    b   c
0  a1   b1  c1
1  a2   b2  c2
2  a3  NaN  c3

a   b   d   c
0  a1  b1  a1  c1
1  a2  b2  a2  c2

### Rename Columns <a class="anchor" id="Rename"></a>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [85]:
display(C)
Cr = C.copy()
Cr.rename(columns = {'country':'C', 'year':'Y'}, inplace = True) 
display(Cr)

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

C     Y   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

### Groupby <a class="anchor" id="Groupby"></a>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.groupby.html <br>
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.agg.html

In [86]:
countries = C.groupby(['country'], as_index=False).mean()
display(countries)
countries.count()


df1 = pd.DataFrame({'A':['yes','yes','yes','yes','no','no','yes','yes','yes','no'],
                   'B':['yes','no','no','no','yes','yes','no','yes','yes','no']})
display(df1)
df1.groupby(['A','B']).size().reset_index().rename(columns={0:'count'})

country    year     cases    population
0  Afghanistan  1999.5    1705.5  2.029122e+07
1       Brazil  1999.5   59112.5  1.732556e+08
2        China  1999.5  213012.0  1.276672e+09

A    B
0  yes  yes
1  yes   no
2  yes   no
3  yes   no
4   no  yes
5   no  yes
6  yes   no
7  yes  yes
8  yes  yes
9   no   no

A    B  count
0   no   no      1
1   no  yes      2
2  yes   no      4
3  yes  yes      3

***Aggregate***

In [87]:
summaries = C.groupby('year').agg(['min', 'max', 'mean', 'median'])
summaries

cases                              population                            \
       min     max          mean median        min         max          mean   
year                                                                           
1999   745  212258  83580.000000  37737   19987071  1272915272  4.883029e+08   
2000  2666  213766  98973.333333  80488   20595360  1280428583  4.918429e+08   

                 
         median  
year             
1999  172006362  
2000  174504898

In [88]:
summaries.columns = ['_'.join(col).strip() for col in summaries.columns.values]
summaries

cases_min  cases_max    cases_mean  cases_median  population_min  \
year                                                                     
1999        745     212258  83580.000000         37737        19987071   
2000       2666     213766  98973.333333         80488        20595360   

      population_max  population_mean  population_median  
year                                                      
1999      1272915272     4.883029e+08          172006362  
2000      1280428583     4.918429e+08          174504898

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rolling.html
https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#window-and-resample-operations

In [89]:
'''Rolling
test = pd.DataFrame({'Timestamp': ['2020-03-12', '2020-03-17', '2020-03-11', '2020-03-15', '2020-03-18', '2020-03-16', '2020-03-13','2020-03-14'], 
              'ST': ['GA', 'GA', 'GA','GA','GA', 'GA', 'GA','GA'],
              'Confirmed': [42,121,17,66,146,99,31,31]})
test = test.sort_values('Timestamp')
test['Timestamp'] = pd.to_datetime(test['Timestamp'])
C.groupby("country").rolling(3).population.mean()
#test['Avg'] = test.rolling(3)#.mean()
'''

'Rolling\ntest = pd.DataFrame({\'Timestamp\': [\'2020-03-12\', \'2020-03-17\', \'2020-03-11\', \'2020-03-15\', \'2020-03-18\', \'2020-03-16\', \'2020-03-13\',\'2020-03-14\'], \n              \'ST\': [\'GA\', \'GA\', \'GA\',\'GA\',\'GA\', \'GA\', \'GA\',\'GA\'],\n              \'Confirmed\': [42,121,17,66,146,99,31,31]})\ntest = test.sort_values(\'Timestamp\')\ntest[\'Timestamp\'] = pd.to_datetime(test[\'Timestamp\'])\nC.groupby("country").rolling(3).population.mean()\n#test[\'Avg\'] = test.rolling(3)#.mean()\n'

### Sort <a class="anchor" id="Sort"></a>
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sort_values.html

In [90]:
sort1 = C.sort_values(by='population', ascending=False) #, ignore_index=False)
display(sort1)
display(C.sort_values(by=['year', 'population']))
sort1.sort_index()

country  year   cases  population
5        China  2000  213766  1280428583
2        China  1999  212258  1272915272
4       Brazil  2000   80488   174504898
1       Brazil  1999   37737   172006362
3  Afghanistan  2000    2666    20595360
0  Afghanistan  1999     745    19987071

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

country  year   cases  population
0  Afghanistan  1999     745    19987071
1       Brazil  1999   37737   172006362
2        China  1999  212258  1272915272
3  Afghanistan  2000    2666    20595360
4       Brazil  2000   80488   174504898
5        China  2000  213766  1280428583

### Saving 
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_excel.html#pandas.DataFrame.to_excel

In [91]:
#df.to_csv('name.csv')

# To excel
#writer = pd.ExcelWriter('name.xlsx')
#df.to_excel(writer, 'Sheet1')
#writer.save()

#df.to_html()
#df.to_json()
#df.to_sql()
#df.to_clipboard() #then paste into excel
#d = df.to_dict()# to dict
#m = df.values   # to numpy

## SQLite <a class="anchor" id="SQLite"></a>

In [96]:
import sqlite3 as db
print(f"* sqlite3 version: {db.version}")

* sqlite3 version: 2.6.0


### Creating Tables

In [97]:
# Connect to a database (or create one if it doesn't exist)
conn = db.connect('example.db')
# conn.close() # Close the SQL database for good measure

# Create a 'cursor' for executing commands
c = conn.cursor()

# If this is not the first time you run this cell, 
# you need to delete the existed "Students" table first
c.execute("DROP TABLE IF EXISTS Students")

# create a table named "Students" with 2 columns: "gtid" and "name".
# the type for column "gtid" is integer and for "name" is text. 
c.execute("CREATE TABLE Students (gtid INTEGER, name TEXT)")
c.execute('DROP TABLE IF EXISTS Takes')
c.execute('CREATE TABLE Takes (gtid INTEGER, course TEXT, grade REAL)')

### Adding Data

In [98]:
c.execute("INSERT INTO Students VALUES (123, 'Vuduc')")
c.execute("INSERT INTO Students VALUES (456, 'Chau')")
c.execute("INSERT INTO Students VALUES (381, 'Bader')")
c.execute("INSERT INTO Students VALUES (991, 'Sokol')")
c.execute("INSERT INTO Takes VALUES (123, 'CSE 6040', 4.0)")
c.execute("INSERT INTO Takes VALUES (991, 'CSE 6040', 4.0)")
c.execute("INSERT INTO Takes VALUES (456, 'CSE 6040', 4.0)")
c.execute("INSERT INTO Takes VALUES (123, 'ISYE 6644', 3.0)")
c.execute("INSERT INTO Takes VALUES (991, 'ISYE 6740', 4.0)")
c.execute("INSERT INTO Takes VALUES (456, 'ISYE 6740', 2.0)")
c.execute("INSERT INTO Takes VALUES (123, 'MGMT 8803', 1.0)")
c.execute("INSERT INTO Takes VALUES (456, 'MGMT 8803', 3.0)")

# An important (and secure!) idiom
more_students = [(723, 'Rozga'),
                 (882, 'Zha'),
                 (401, 'Park'),
                 (377, 'Vetter'),
                 (904, 'Brown')]

# '?' question marks are placeholders for the two columns in Students table
c.executemany('INSERT INTO Students VALUES (?, ?)', more_students)

# Changes aren't made until they're committed
conn.commit()

### Query Data

In [99]:
c.execute("SELECT * FROM Students")
results = c.fetchall()
print("Your results:", len(results), "\nThe entries of Students:\n", results)

# Displays the results of your code
c.execute('SELECT * FROM Takes')
results = c.fetchall()
print("Your results:", len(results), "\nThe entries of Takes:", results)

Your results: 9 
The entries of Students:
 [(123, 'Vuduc'), (456, 'Chau'), (381, 'Bader'), (991, 'Sokol'), (723, 'Rozga'), (882, 'Zha'), (401, 'Park'), (377, 'Vetter'), (904, 'Brown')]
Your results: 8 
The entries of Takes: [(123, 'CSE 6040', 4.0), (991, 'CSE 6040', 4.0), (456, 'CSE 6040', 4.0), (123, 'ISYE 6644', 3.0), (991, 'ISYE 6740', 4.0), (456, 'ISYE 6740', 2.0), (123, 'MGMT 8803', 1.0), (456, 'MGMT 8803', 3.0)]


### Join Queries <a class="anchor" id="Join Queries"></a>

The main type of query that combines information from multiple tables is the _join query_. Recall from our discussion of tibbles these four types:

- `INNER JOIN(A, B)`: Keep rows of `A` and `B` only where `A` and `B` match
- `OUTER JOIN(A, B)`: Keep all rows of `A` and `B`, but merge matching rows and fill in missing values with some default (`NaN` in Pandas, `NULL` in SQL)
- `LEFT JOIN(A, B)`: Keep all rows of `A` but only merge matches from `B`.
- `RIGHT JOIN(A, B)`: Keep all rows of `B` but only merge matches from `A`.

If you are a visual person, see [this page](https://www.codeproject.com/Articles/33052/Visual-Representation-of-SQL-Joins) for illustrations of the different join types.

In SQL, you can use the `WHERE` clause of a `SELECT` statement to specify how to match rows from the tables being joined. For example, recall that the `Takes` table stores classes taken by each student. However, these classes are recorded by a student's GT ID. Suppose we want a report where we want each student's name rather than his/her ID. We can get the matching name from the `Students` table. Here is a query to accomplish this matching:

In [100]:
# See all (name, course, grade) tuples
query = '''
        SELECT Students.name, Takes.course, Takes.grade
        FROM Students, Takes
        WHERE Students.gtid = Takes.gtid'''

for match in c.execute(query): # Note this alternative idiom for iterating over query results
    print(match)

('Vuduc', 'CSE 6040', 4.0)
('Vuduc', 'ISYE 6644', 3.0)
('Vuduc', 'MGMT 8803', 1.0)
('Chau', 'CSE 6040', 4.0)
('Chau', 'ISYE 6740', 2.0)
('Chau', 'MGMT 8803', 3.0)
('Sokol', 'CSE 6040', 4.0)
('Sokol', 'ISYE 6740', 4.0)


In [101]:
query = '''
        SELECT Students.name, Takes.grade
        FROM Students, Takes
        WHERE Students.gtid = Takes.gtid and Takes.course = 'CSE 6040'
        '''

c.execute(query)
results1= c.fetchall()
results1

[('Vuduc', 4.0), ('Sokol', 4.0), ('Chau', 4.0)]

In [102]:
query = '''
        SELECT Students.name, Takes.grade
        FROM Students 
        LEFT JOIN Takes on Students.gtid = Takes.gtid
'''

# Executes your `query` string:
c.execute(query)
matches = c.fetchall()
for i, match in enumerate(matches):
    print(i, "->", match)

0 -> ('Vuduc', 1.0)
1 -> ('Vuduc', 3.0)
2 -> ('Vuduc', 4.0)
3 -> ('Chau', 2.0)
4 -> ('Chau', 3.0)
5 -> ('Chau', 4.0)
6 -> ('Bader', None)
7 -> ('Sokol', 4.0)
8 -> ('Sokol', 4.0)
9 -> ('Rozga', None)
10 -> ('Zha', None)
11 -> ('Park', None)
12 -> ('Vetter', None)
13 -> ('Brown', None)


In [103]:
# Examples that don't work because no database :(
query = '''
SELECT 
    LOWER(ComplaintType) as type
    ,COUNT(ComplaintType) AS freq 
    FROM data 
    GROUP BY type
    ORDER BY freq DESC 
'''

# `COLLATE NOCASE` is a case-insensitive qualifier.
query = '''
  SELECT UPPER(City) AS name, COUNT(*) AS freq
    FROM data
    WHERE name <> 'None'
    GROUP BY City COLLATE NOCASE
    ORDER BY -freq
    LIMIT 10
'''

# Dates and times
query = '''
  SELECT LOWER(ComplaintType), CreatedDate, UPPER(City)
    from data
    where CreatedDate >= "2015-09-15 00:00:00.0"
      and CreatedDate < "2015-09-16 00:00:00.0"
    order by CreatedDate
'''

# Extract the hour from the time stamp
query = '''
  SELECT CreatedDate, STRFTIME('%H', CreatedDate) AS Hour, LOWER(ComplaintType)
    FROM data
    LIMIT 5
'''

# Runs your `query`:
#df_complaint_freq = pd.read_sql_query(query, disk_engine)
#df_complaint_freq.head()

In [104]:
c.close()
conn.close()